apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vqoagc96a-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vqoagc96a-nodejs 
  name: vqoagc96a-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: vqoagc96a-nodejs 
